version: '2'
services:
  # api:
  #   image: data-stack-api
  # db:
  #   image: postgres
  ui:
    build: .
    image: data-stack-ui:5
    volumes:
      - .:/app/ui
    ports:
      - "8080:8080"
  #   depends_on:
  #     - db
  #     - api